// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: room/proto/room.proto

package roompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Booking       []*Booking             `protobuf:"bytes,5,rep,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_proto_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Room) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Room) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Room) GetBooking() []*Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_room_proto_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{1}
}

func (x *Booking) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_proto_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_room_proto_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_proto_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_room_proto_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type GetAllRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRoomsRequest) Reset() {
	*x = GetAllRoomsRequest{}
	mi := &file_room_proto_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomsRequest) ProtoMessage() {}

func (x *GetAllRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetAllRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{6}
}

type GetAllRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRoomsResponse) Reset() {
	*x = GetAllRoomsResponse{}
	mi := &file_room_proto_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomsResponse) ProtoMessage() {}

func (x *GetAllRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetAllRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type UpdatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceRequest) Reset() {
	*x = UpdatePriceRequest{}
	mi := &file_room_proto_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceRequest) ProtoMessage() {}

func (x *UpdatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePriceRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePriceRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *UpdatePriceRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdatePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceResponse) Reset() {
	*x = UpdatePriceResponse{}
	mi := &file_room_proto_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceResponse) ProtoMessage() {}

func (x *UpdatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePriceResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePriceResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type AddBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Booking       *Booking               `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookingRequest) Reset() {
	*x = AddBookingRequest{}
	mi := &file_room_proto_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookingRequest) ProtoMessage() {}

func (x *AddBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookingRequest.ProtoReflect.Descriptor instead.
func (*AddBookingRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{10}
}

func (x *AddBookingRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *AddBookingRequest) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type AddBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookingResponse) Reset() {
	*x = AddBookingResponse{}
	mi := &file_room_proto_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookingResponse) ProtoMessage() {}

func (x *AddBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookingResponse.ProtoReflect.Descriptor instead.
func (*AddBookingResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{11}
}

func (x *AddBookingResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingRequest) Reset() {
	*x = DeleteBookingRequest{}
	mi := &file_room_proto_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingRequest) ProtoMessage() {}

func (x *DeleteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookingRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBookingRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *DeleteBookingRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type DeleteBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingResponse) Reset() {
	*x = DeleteBookingResponse{}
	mi := &file_room_proto_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingResponse) ProtoMessage() {}

func (x *DeleteBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBookingResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_room_proto_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRoomRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_room_proto_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_room_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRoomResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_room_proto_room_proto protoreflect.FileDescriptor

const file_room_proto_room_proto_rawDesc = "" +
	"\n" +
	"\x15room/proto/room.proto\x12\x04room\"\x81\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12'\n" +
	"\abooking\x18\x05 \x03(\v2\r.room.bookingR\abooking\"\x1d\n" +
	"\abooking\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"3\n" +
	"\x11CreateRoomRequest\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\"4\n" +
	"\x12CreateRoomResponse\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\"(\n" +
	"\x0eGetRoomRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"1\n" +
	"\x0fGetRoomResponse\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\"\x14\n" +
	"\x12GetAllRoomsRequest\"7\n" +
	"\x13GetAllRoomsResponse\x12 \n" +
	"\x05rooms\x18\x01 \x03(\v2\n" +
	".room.RoomR\x05rooms\"B\n" +
	"\x12UpdatePriceRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\"5\n" +
	"\x13UpdatePriceResponse\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\"T\n" +
	"\x11AddBookingRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12'\n" +
	"\abooking\x18\x02 \x01(\v2\r.room.bookingR\abooking\"4\n" +
	"\x12AddBookingResponse\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\"B\n" +
	"\x14DeleteBookingRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"7\n" +
	"\x15DeleteBookingResponse\x12\x1e\n" +
	"\x04room\x18\x01 \x01(\v2\n" +
	".room.RoomR\x04room\"+\n" +
	"\x11DeleteRoomRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\",\n" +
	"\x12DeleteRoomResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xda\x03\n" +
	"\vRoomService\x12?\n" +
	"\n" +
	"CreateRoom\x12\x17.room.CreateRoomRequest\x1a\x18.room.CreateRoomResponse\x126\n" +
	"\aGetRoom\x12\x14.room.GetRoomRequest\x1a\x15.room.GetRoomResponse\x12B\n" +
	"\vGetAllRooms\x12\x18.room.GetAllRoomsRequest\x1a\x19.room.GetAllRoomsResponse\x12B\n" +
	"\vUpdatePrice\x12\x18.room.UpdatePriceRequest\x1a\x19.room.UpdatePriceResponse\x12?\n" +
	"\n" +
	"AddBooking\x12\x17.room.AddBookingRequest\x1a\x18.room.AddBookingResponse\x12H\n" +
	"\rDeleteBooking\x12\x1a.room.DeleteBookingRequest\x1a\x1b.room.DeleteBookingResponse\x12?\n" +
	"\n" +
	"DeleteRoom\x12\x17.room.DeleteRoomRequest\x1a\x18.room.DeleteRoomResponseB\x13Z\x11room/proto;roompbb\x06proto3"

var (
	file_room_proto_room_proto_rawDescOnce sync.Once
	file_room_proto_room_proto_rawDescData []byte
)

func file_room_proto_room_proto_rawDescGZIP() []byte {
	file_room_proto_room_proto_rawDescOnce.Do(func() {
		file_room_proto_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_room_proto_rawDesc), len(file_room_proto_room_proto_rawDesc)))
	})
	return file_room_proto_room_proto_rawDescData
}

var file_room_proto_room_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_room_proto_room_proto_goTypes = []any{
	(*Room)(nil),                  // 0: room.Room
	(*Booking)(nil),               // 1: room.booking
	(*CreateRoomRequest)(nil),     // 2: room.CreateRoomRequest
	(*CreateRoomResponse)(nil),    // 3: room.CreateRoomResponse
	(*GetRoomRequest)(nil),        // 4: room.GetRoomRequest
	(*GetRoomResponse)(nil),       // 5: room.GetRoomResponse
	(*GetAllRoomsRequest)(nil),    // 6: room.GetAllRoomsRequest
	(*GetAllRoomsResponse)(nil),   // 7: room.GetAllRoomsResponse
	(*UpdatePriceRequest)(nil),    // 8: room.UpdatePriceRequest
	(*UpdatePriceResponse)(nil),   // 9: room.UpdatePriceResponse
	(*AddBookingRequest)(nil),     // 10: room.AddBookingRequest
	(*AddBookingResponse)(nil),    // 11: room.AddBookingResponse
	(*DeleteBookingRequest)(nil),  // 12: room.DeleteBookingRequest
	(*DeleteBookingResponse)(nil), // 13: room.DeleteBookingResponse
	(*DeleteRoomRequest)(nil),     // 14: room.DeleteRoomRequest
	(*DeleteRoomResponse)(nil),    // 15: room.DeleteRoomResponse
}
var file_room_proto_room_proto_depIdxs = []int32{
	1,  // 0: room.Room.booking:type_name -> room.booking
	0,  // 1: room.CreateRoomRequest.room:type_name -> room.Room
	0,  // 2: room.CreateRoomResponse.room:type_name -> room.Room
	0,  // 3: room.GetRoomResponse.room:type_name -> room.Room
	0,  // 4: room.GetAllRoomsResponse.rooms:type_name -> room.Room
	0,  // 5: room.UpdatePriceResponse.room:type_name -> room.Room
	1,  // 6: room.AddBookingRequest.booking:type_name -> room.booking
	0,  // 7: room.AddBookingResponse.room:type_name -> room.Room
	0,  // 8: room.DeleteBookingResponse.room:type_name -> room.Room
	2,  // 9: room.RoomService.CreateRoom:input_type -> room.CreateRoomRequest
	4,  // 10: room.RoomService.GetRoom:input_type -> room.GetRoomRequest
	6,  // 11: room.RoomService.GetAllRooms:input_type -> room.GetAllRoomsRequest
	8,  // 12: room.RoomService.UpdatePrice:input_type -> room.UpdatePriceRequest
	10, // 13: room.RoomService.AddBooking:input_type -> room.AddBookingRequest
	12, // 14: room.RoomService.DeleteBooking:input_type -> room.DeleteBookingRequest
	14, // 15: room.RoomService.DeleteRoom:input_type -> room.DeleteRoomRequest
	3,  // 16: room.RoomService.CreateRoom:output_type -> room.CreateRoomResponse
	5,  // 17: room.RoomService.GetRoom:output_type -> room.GetRoomResponse
	7,  // 18: room.RoomService.GetAllRooms:output_type -> room.GetAllRoomsResponse
	9,  // 19: room.RoomService.UpdatePrice:output_type -> room.UpdatePriceResponse
	11, // 20: room.RoomService.AddBooking:output_type -> room.AddBookingResponse
	13, // 21: room.RoomService.DeleteBooking:output_type -> room.DeleteBookingResponse
	15, // 22: room.RoomService.DeleteRoom:output_type -> room.DeleteRoomResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_room_proto_room_proto_init() }
func file_room_proto_room_proto_init() {
	if File_room_proto_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_room_proto_rawDesc), len(file_room_proto_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_room_proto_goTypes,
		DependencyIndexes: file_room_proto_room_proto_depIdxs,
		MessageInfos:      file_room_proto_room_proto_msgTypes,
	}.Build()
	File_room_proto_room_proto = out.File
	file_room_proto_room_proto_goTypes = nil
	file_room_proto_room_proto_depIdxs = nil
}
